### ISSUE TITLE
`nouns` contains some words with punctuation.

### ISSUE THREAD

**Issue by rampion** [iand675/haikunator#3]
Specifically `butterfly–`, `darkly–`, `darkness-`, and `depth–`.

This can generate some weird looking slugs.

**Comment by iand675** [comment]
@rampion https://github.com/iand675/haikunator/blob/4fc77eaf0bbac20766b9cd10e71271bd7df67bbc/nouns#L141 I don't see evidence of that in the word list. Any chance you can provide more of a repro of the full slug?

**Comment by rampion** [comment]
Ah, this was in 0.1.1.0, looks like @rshaked culled it [here](https://github.com/iand675/haikunator/commit/ca0ca9dac8601482f345f0c8f991f076f630e392)

![image](https://github.com/user-attachments/assets/3af3b501-4497-4246-9490-93e8e1020eb1)

**Comment by rampion** [comment]
Using an out of date version!
